export const CATEGORIES = [
  "Ev və Mətbəx",
  "Qadın Geyimləri",
  "Böyük Bədən Qadın Geyimləri",
  "Qadın Ayaqqabıları",
  "Qadın Alt Paltarları və Ev Geyimləri",
  "Kişi Geyimləri",
  "Kişi Ayaqqabıları",
  "Kişi Böyük Bədən Geyimləri",
  "Kişi Alt Paltarı və Pijaması",
  "İdman və Açıq Hava Fəaliyyətləri",
  "Zinət Əşyaları və Aksesuarlar",
  "Gözəllik və Sağlamlıq",
  "Oyuncaqlar və Oyunlar",
  "Avtomobil",
  "Uşaq Dəbi",
  "Uşaq Ayaqqabıları",
  "Körpə və Ana",
  "Çantalar və Baqaj",
  "Həyət, Bağ və Bağça",
  "İncəsənət, Sənətkarlıq və Tikiş",
  "Elektronika",
  "Sənaye və Kommersiya",
  "Alətlər və Ev Təkmilləşdirmə",
  "Cihazlar",
  "Ofis və Məktəb Ləvazimatları",
  "Sağlamlıq və Məişət",
  "Ev Heyvanları Ləvazimatları",
  "Mobil Telefonlar və Aksesuarlar",
  "Ağıllı Ev",
  "Musiqi Alətləri",
  "Qida və Baqqal",
  "Kitablar və Media",
  "Çimərlik Geyimi",
  "Mebel"
];
